//Statyczna tablica memów

const memData = [
  {
    title: "Mem 1",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem1.jpg",
    favorite: false,
  },
  {
    title: "Mem 2",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem2.jpg",
    favorite: false,
  },
  {
    title: "Mem 3",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem3.jpg",
    favorite: false,
  },
  {
    title: "Mem 4",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem4.jpg",
    favorite: false,
  },
  {
    title: "Mem 5",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem5.jpg",
    favorite: false,
  },
  {
    title: "Mem 6",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem6.jpg",
    favorite: false,
  },
  {
    title: "Mem 7",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem7.jpg",
    favorite: false,
  },
  {
    title: "Mem 8",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem8.jpg",
    favorite: false,
  },
  {
    title: "Mem 9",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem9.jpg",
    favorite: false,
  },
  {
    title: "Mem 10",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem10.jpg",
    favorite: false,
  },
  {
    title: "Mem 11",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem11.jpg",
    favorite: false,
  },
  {
    title: "Mem 12",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem12.jpg",
    favorite: false,
  },
  {
    title: "Mem 13",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem13.jpg",
    favorite: false,
  },
  {
    title: "Mem 14",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem14.jpg",
    favorite: false,
  },
  {
    title: "Mem 15",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem15.jpg",
    favorite: false,
  },
  {
    title: "Mem 16",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem16.jpg",
    favorite: false,
  },
  {
    title: "Mem 17",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem17.jpg",
    favorite: false,
  },
  {
    title: "Mem 18",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem18.jpg",
    favorite: false,
  },
  {
    title: "Mem 19",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem19.jpg",
    favorite: false,
  },
  {
    title: "Mem 20",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem20.jpg",
    favorite: false,
  },
  {
    title: "Mem 21",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem21.jpg",
    favorite: false,
  },
  {
    title: "Mem 22",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem22.jpg",
    favorite: false,
  },
  {
    title: "Mem 23",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem23.jpg",
    favorite: false,
  },
  {
    title: "Mem 24",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem24.jpg",
    favorite: false,
  },
  {
    title: "Mem 25",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem25.jpg",
    favorite: false,
  },
  {
    title: "Mem 26",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem26.jpg",
    favorite: false,
  },
  {
    title: "Mem 27",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem27.jpg",
    favorite: false,
  },
  {
    title: "Mem 28",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem28.jpg",
    favorite: false,
  },
  {
    title: "Mem 29",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem29.jpg",
    favorite: false,
  },
  {
    title: "Mem 30",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem30.jpg",
    favorite: false,
  },
  {
    title: "Mem 31",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem31.jpg",
    favorite: false,
  },
  {
    title: "Mem 32",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem32.jpg",
    favorite: false,
  },
  {
    title: "Mem 33",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem33.jpg",
    favorite: false,
  },
];

export default memData;
