//Constant meme database

const memData = [
  {
    id: 1,
    title: "Mem 1",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem1.jpg",
    favorite: false,
  },
  {
    id: 2,
    title: "Mem 2",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem2.jpg",
    favorite: false,
  },
  {
    id: 3,
    title: "Mem 3",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem3.jpg",
    favorite: false,
  },
  {
    id: 4,
    title: "Mem 4",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem4.jpg",
    favorite: false,
  },
  {
    id: 5,
    title: "Mem 5",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem5.jpg",
    favorite: false,
  },
  {
    id: 6,
    title: "Mem 6",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem6.jpg",
    favorite: false,
  },
  {
    id: 7,
    title: "Mem 7",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem7.jpg",
    favorite: false,
  },
  {
    id: 8,
    title: "Mem 8",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem8.jpg",
    favorite: false,
  },
  {
    id: 9,
    title: "Mem 9",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem9.jpg",
    favorite: false,
  },
  {
    id: 10,
    title: "Mem 10",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem10.jpg",
    favorite: false,
  },
  {
    id: 11,
    title: "Mem 11",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem11.jpg",
    favorite: false,
  },
  {
    id: 12,
    title: "Mem 12",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem12.jpg",
    favorite: false,
  },
  {
    id: 13,
    title: "Mem 13",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem13.jpg",
    favorite: false,
  },
  {
    id: 14,
    title: "Mem 14",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem14.jpg",
    favorite: false,
  },
  {
    id: 15,
    title: "Mem 15",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem15.jpg",
    favorite: false,
  },
  {
    id: 16,
    title: "Mem 16",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem16.jpg",
    favorite: false,
  },
  {
    id: 17,
    title: "Mem 17",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem17.jpg",
    favorite: false,
  },
  {
    id: 18,
    title: "Mem 18",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem18.jpg",
    favorite: false,
  },
  {
    id: 19,
    title: "Mem 19",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem19.jpg",
    favorite: false,
  },
  {
    id: 20,
    title: "Mem 20",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem20.jpg",
    favorite: false,
  },
  {
    id: 21,
    title: "Mem 21",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem21.jpg",
    favorite: false,
  },
  {
    id: 22,
    title: "Mem 22",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem22.jpg",
    favorite: false,
  },
  {
    id: 23,
    title: "Mem 23",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem23.jpg",
    favorite: false,
  },
  {
    id: 24,
    title: "Mem 24",
    upvotes: 7,
    downvotes: 1,
    img: "/images/mem24.jpg",
    favorite: false,
  },
  {
    id: 25,
    title: "Mem 25",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem25.jpg",
    favorite: false,
  },
  {
    id: 26,
    title: "Mem 26",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem26.jpg",
    favorite: false,
  },
  {
    id: 27,
    title: "Mem 27",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem27.jpg",
    favorite: false,
  },
  {
    id: 28,
    title: "Mem 28",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem28.jpg",
    favorite: false,
  },
  {
    id: 29,
    title: "Mem 29",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem29.jpg",
    favorite: false,
  },
  {
    id: 30,
    title: "Mem 30",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem30.jpg",
    favorite: false,
  },
  {
    id: 31,
    title: "Mem 31",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem31.jpg",
    favorite: false,
  },
  {
    id: 32,
    title: "Mem 32",
    upvotes: 0,
    downvotes: 0,
    img: "/images/mem32.jpg",
    favorite: false,
  },
  {
    id: 33,
    title: "Mem 33",
    upvotes: 10,
    downvotes: 0,
    img: "/images/mem33.jpg",
    favorite: false,
  },
];

export default memData;
